### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jvanstraten** [abs-tudelft/wiki-search-alveo#4]
List of things to do (also includes nice-to-haves)

## Web interface

 - [x] add links to wikipedia articles
 - [x] cache images retrieved from wikipedia's API locally for increased speed
 - [ ] allow running both software and hardware implementations automatically
 - [ ] bar plot for hardware vs software
     - [x] rudimentary implementation
     - [ ] tick marks (probably requires some kind of plotting device)
     - [x] don't rely on javascript `setInterval()` accuracy for animation (chromium seems to be accurate, waterfox is not)
     - [ ] implement websocket-based push notifications to allow the web app to delay starting the bar graph timer until the run actually starts
 - [ ] locking the server to allow multiple client connections
     - [ ] a proper queue?
 - [ ] language switching
 - [ ] status display
     - [x] rudimentary server status display using polling
     - [ ] handle and indicate errors when the server goes offline, and automatically restart polling or show a button to do so
     - [ ] use websocket-based push notifications for the status display
     - [ ] add CPU utilization meter (this is easier if there is just some thread running that generates the push notifications, because of the required averaging window)
     - [ ] make a nice plot instead of just having bars
 - [ ] proper error handling (right now, the client tries to interpret a failure message as JSON, so the script crashes)
 - [ ] demo-mode that automatically requests things every so often
 - [x] architecture/information page(s)

## FPGA implementation

 - [ ] allow pattern matching (wildcards etc)
 - [ ] actually fill up the FPGA to get more performance
     - [ ] figure out why memory is bottlenecking at around 50% theoretical (burst size, probably)
     - [ ] four instead of three subkernels, or do a simpler kind of duplication

## Clean up
 - [x] make sure readme is up-to-date
 - [x] move to abs-tudelft, open repository
